"""
Assembles the final markdown report from all components.
"""

import os
from datetime import datetime
from src.narrator.generator import NarratorResult
from src.report.charts import plot_loss_curves, plot_learning_rate


REPORT_TEMPLATE = """# ExpLens Report: {run_name}
*Generated {timestamp} by ExpLens*

---

## Overview

{overview}

---

## Training Configuration

| Parameter | Value |
|-----------|-------|
{config_table}

---

## Training Curves

![Loss Curves]({loss_curves_path})
{lr_chart_section}

---

## Training Dynamics

{training_dynamics}

---

{generalisation_section}

## Detected Patterns

{patterns_section}

---

## Recommendations

{recommendations}

---

## What to Try Next

{what_next}

---

## Consistency Check

{consistency_section}

---
*Report generated by [ExpLens](https://github.com/aeesh/explens)*
"""

