"""
Assembles the final markdown report from all components.
"""

import os
from datetime import datetime
from src.narrator.generator import NarratorResult
from src.report.charts import plot_loss_curves, plot_learning_rate


REPORT_TEMPLATE = """# ExpLens Report: {run_name}
*Generated {timestamp} by ExpLens*

---

## Overview

{overview}

---

## Training Configuration

| Parameter | Value |
|-----------|-------|
{config_table}

---

## Training Curves

![Loss Curves]({loss_curves_path})
{lr_chart_section}

---

## Training Dynamics

{training_dynamics}

---

{generalisation_section}

## Detected Patterns

{patterns_section}

---

## Recommendations

{recommendations}

---

## What to Try Next

{what_next}

---

## Consistency Check

{consistency_section}

---
*Report generated by [ExpLens](https://github.com/aeesh/explens)*
"""


def build_report(result: NarratorResult, output_dir: str) -> str:
    """Build and save the full markdown report. Returns path to report."""
    os.makedirs(output_dir, exist_ok=True)
    run = result.facts.run

    # Generate charts
    loss_curves_path = plot_loss_curves(run, output_dir)
    lr_path = plot_learning_rate(run, output_dir)

    # Config table
    config_rows = "\n".join(
        f"| {k} | {v} |"
        for k, v in run.config.items()
        if not k.startswith("_")
    )

    # LR chart section
    lr_section = ""
    if lr_path:
        lr_section = f"\n![Learning Rate]({lr_path})\n"

    # Generalisation section
    gen_section = ""
    if result.generalisation:
        gen_section = f"## Generalisation\n\n{result.generalisation}\n\n---\n\n"

